### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-form#61]
there is no need to use jquery. i propose removing it

till/else then it needs to be a dependency

**Comment by bas080** [comment]
I agree that it should be removed. I also want to alter the setting of attributes on elements. It's not flexible enough currently. What happens now is the following.

``` js
let someSchema = [{
  key: 'username',
  attributes: {
    class: 'form-control highlighted'
  }
}];
```

Because I'm setting the class attribute I have to repeat classes that I want to keep. Not terrible but redundant.

I'm also not able to do DOM element selections and manipulate them using the full browser DOM api.

I believe a good alternative is to have a `render` function which returns the form-field's element as a callback. example

``` js
let someSchema = [{
  key: 'username',
  render: element => {
    element.getElementsByTagName('input')[0].classList.add('highlight');
  }
}];
```

By implementing the manipulation of Dom like this we can leave it up to the user to use jquery or the native DOM api.

I do think that for certain use cases the `attributes` property defined on the element is convenient. So we would have to remove the jquery dependency.

**Comment by RWOverdijk** [comment]
I think we can just remove jquery, and assign the attributes ourselves. I want to keep it simple.

As to repeating classes, same thing, I think that's fine. The user can _choose_ to use render or use class and repeat the class names.
